name: Paul Rosania
markdown: redcarpet
highlighter: true
host: paul.rosania.org
baseurl: /writings
permalink: /:year/:month/:day/:title
author:
  name: Paul Rosania
  email: paul@rosania.org
  url: http://paul.rosania.org
